//
//  BusSchedule.swift
//  SUSTechFlow
//
//  Created by Wycer on 2020/11/29.
//

import Foundation

struct BusRoute: Identifiable {
    let id = UUID()
    let start: String
    let end: String
    let isPeak: Bool
    let schedules: [BusSchedule]
}

let busRoute1 = BusRoute(
    start: "科研楼", end: "欣园", isPeak: false, schedules: [
        BusSchedule(
            type: BusScheduleType.WorkingDay, entries: [
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 25)),
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 46)),
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 50)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 05)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 13)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 16)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 22)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 25)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 28)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 32)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 34)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 36)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 38)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 42)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 45)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 48)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 51)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 54)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 57)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 03)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 06)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 15)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 25)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 35)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 45)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 50)),
                BusScheduleEntry(time: BusScheduleTime(h: 10, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 10, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 10, m: 15)),
                BusScheduleEntry(time: BusScheduleTime(h: 10, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 10, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 10, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 10, m: 45)),
                BusScheduleEntry(time: BusScheduleTime(h: 10, m: 50)),
                BusScheduleEntry(time: BusScheduleTime(h: 11, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 11, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 11, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 11, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 11, m: 35)),
                BusScheduleEntry(time: BusScheduleTime(h: 11, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 11, m: 45)),
                BusScheduleEntry(time: BusScheduleTime(h: 11, m: 50)),
                BusScheduleEntry(time: BusScheduleTime(h: 11, m: 55)),
                BusScheduleEntry(time: BusScheduleTime(h: 12, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 12, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 12, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 12, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 12, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 12, m: 45)),
                BusScheduleEntry(time: BusScheduleTime(h: 12, m: 55)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 05)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 15)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 25)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 35)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 50)),
                BusScheduleEntry(time: BusScheduleTime(h: 14, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 14, m: 05)),
                BusScheduleEntry(time: BusScheduleTime(h: 14, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 14, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 14, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 14, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 14, m: 50)),
                BusScheduleEntry(time: BusScheduleTime(h: 15, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 15, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 15, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 15, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 15, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 15, m: 45)),
                BusScheduleEntry(time: BusScheduleTime(h: 15, m: 55)),
                BusScheduleEntry(time: BusScheduleTime(h: 16, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 16, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 16, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 16, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 16, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 16, m: 50)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 15)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 25)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 35)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 45)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 50)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 55)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 23)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 35)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 50)),
                BusScheduleEntry(time: BusScheduleTime(h: 19, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 19, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 19, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 19, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 19, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 19, m: 50)),
                BusScheduleEntry(time: BusScheduleTime(h: 20, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 20, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 20, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 21, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 21, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 21, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 21, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 22, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 22, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 22, m: 45)),
                BusScheduleEntry(time: BusScheduleTime(h: 23, m: 00))
            ]),
        BusSchedule(
            type: BusScheduleType.Holiday, entries: [
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 15)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 45)),
                BusScheduleEntry(time: BusScheduleTime(h: 10, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 10, m: 15)),
                BusScheduleEntry(time: BusScheduleTime(h: 10, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 10, m: 45)),
                BusScheduleEntry(time: BusScheduleTime(h: 11, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 11, m: 15)),
                BusScheduleEntry(time: BusScheduleTime(h: 11, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 11, m: 45)),
                BusScheduleEntry(time: BusScheduleTime(h: 12, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 12, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 12, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 14, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 14, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 14, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 15, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 15, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 15, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 16, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 16, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 16, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 15)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 45)),
                BusScheduleEntry(time: BusScheduleTime(h: 19, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 19, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 19, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 20, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 20, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 20, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 21, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 21, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 21, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 22, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 22, m: 20))
            ]),
    ])



let busRoute2 = BusRoute(
    start: "科研楼", end: "欣园", isPeak: true, schedules: [BusSchedule(
        type: BusScheduleType.WorkingDay, entries: [
            BusScheduleEntry(time: BusScheduleTime(h: 07, m: 35)),
            BusScheduleEntry(time: BusScheduleTime(h: 07, m: 43)),
            BusScheduleEntry(time: BusScheduleTime(h: 07, m: 55)),
            BusScheduleEntry(time: BusScheduleTime(h: 09, m: 53)),
            BusScheduleEntry(time: BusScheduleTime(h: 09, m: 56)),
            BusScheduleEntry(time: BusScheduleTime(h: 10, m: 03)),
            BusScheduleEntry(time: BusScheduleTime(h: 10, m: 06)),
            BusScheduleEntry(time: BusScheduleTime(h: 12, m: 05)),
            BusScheduleEntry(time: BusScheduleTime(h: 12, m: 13)),
            BusScheduleEntry(time: BusScheduleTime(h: 12, m: 16)),
            BusScheduleEntry(time: BusScheduleTime(h: 12, m: 25)),
            BusScheduleEntry(time: BusScheduleTime(h: 12, m: 33)),
            BusScheduleEntry(time: BusScheduleTime(h: 12, m: 36)),
            BusScheduleEntry(time: BusScheduleTime(h: 12, m: 50)),
            BusScheduleEntry(time: BusScheduleTime(h: 13, m: 45)),
            BusScheduleEntry(time: BusScheduleTime(h: 13, m: 53)),
            BusScheduleEntry(time: BusScheduleTime(h: 13, m: 56)),
            BusScheduleEntry(time: BusScheduleTime(h: 14, m: 15)),
            BusScheduleEntry(time: BusScheduleTime(h: 15, m: 50)),
            BusScheduleEntry(time: BusScheduleTime(h: 16, m: 03)),
            BusScheduleEntry(time: BusScheduleTime(h: 16, m: 06)),
            BusScheduleEntry(time: BusScheduleTime(h: 18, m: 05)),
            BusScheduleEntry(time: BusScheduleTime(h: 18, m: 13)),
            BusScheduleEntry(time: BusScheduleTime(h: 18, m: 16)),
            BusScheduleEntry(time: BusScheduleTime(h: 18, m: 26)),
            BusScheduleEntry(time: BusScheduleTime(h: 18, m: 40)),
            BusScheduleEntry(time: BusScheduleTime(h: 20, m: 55)),
            BusScheduleEntry(time: BusScheduleTime(h: 21, m: 03)),
            BusScheduleEntry(time: BusScheduleTime(h: 21, m: 53)),
            BusScheduleEntry(time: BusScheduleTime(h: 21, m: 56)),
            BusScheduleEntry(time: BusScheduleTime(h: 22, m: 10))
        ]
    )])





let busRoute3 = BusRoute(
    start: "欣园", end: "科研楼", isPeak: false, schedules: [
        BusSchedule(
            type: BusScheduleType.WorkingDay, entries: [
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 05)),
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 29)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 05)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 15)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 18)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 21)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 24)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 27)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 35)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 45)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 48)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 51)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 54)),
                BusScheduleEntry(time: BusScheduleTime(h: 08, m: 57)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 05)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 15)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 25)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 35)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 50)),
                BusScheduleEntry(time: BusScheduleTime(h: 10, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 10, m: 05)),
                BusScheduleEntry(time: BusScheduleTime(h: 10, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 10, m: 15)),
                BusScheduleEntry(time: BusScheduleTime(h: 10, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 10, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 10, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 10, m: 50)),
                BusScheduleEntry(time: BusScheduleTime(h: 11, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 11, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 11, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 11, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 11, m: 35)),
                BusScheduleEntry(time: BusScheduleTime(h: 11, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 11, m: 45)),
                BusScheduleEntry(time: BusScheduleTime(h: 11, m: 50)),
                BusScheduleEntry(time: BusScheduleTime(h: 11, m: 55)),
                BusScheduleEntry(time: BusScheduleTime(h: 12, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 12, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 12, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 12, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 12, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 12, m: 50)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 05)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 50)),
                BusScheduleEntry(time: BusScheduleTime(h: 14, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 14, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 14, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 14, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 14, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 14, m: 50)),
                BusScheduleEntry(time: BusScheduleTime(h: 15, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 15, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 15, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 15, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 15, m: 35)),
                BusScheduleEntry(time: BusScheduleTime(h: 15, m: 50)),
                BusScheduleEntry(time: BusScheduleTime(h: 16, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 16, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 16, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 16, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 16, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 16, m: 50)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 15)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 23)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 26)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 33)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 36)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 43)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 46)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 50)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 53)),
                BusScheduleEntry(time: BusScheduleTime(h: 17, m: 56)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 03)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 06)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 13)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 16)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 35)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 45)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 50)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 55)),
                BusScheduleEntry(time: BusScheduleTime(h: 19, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 19, m: 10)),
                BusScheduleEntry(time: BusScheduleTime(h: 19, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 19, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 19, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 19, m: 50)),
                BusScheduleEntry(time: BusScheduleTime(h: 20, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 20, m: 15)),
                BusScheduleEntry(time: BusScheduleTime(h: 20, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 20, m: 45)),
                BusScheduleEntry(time: BusScheduleTime(h: 21, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 21, m: 20)),
                BusScheduleEntry(time: BusScheduleTime(h: 21, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 22, m: 00)),
                BusScheduleEntry(time: BusScheduleTime(h: 22, m: 15)),
                BusScheduleEntry(time: BusScheduleTime(h: 22, m: 30)),
                BusScheduleEntry(time: BusScheduleTime(h: 22, m: 40))
            ]),
        BusSchedule(
            type: BusScheduleType.Holiday, entries: [
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 15)),
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 23)),
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 26)),
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 32)),
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 36)),
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 39)),
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 42)),
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 45)),
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 48)),
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 51)),
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 54)),
                BusScheduleEntry(time: BusScheduleTime(h: 07, m: 57)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 43)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 46)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 53)),
                BusScheduleEntry(time: BusScheduleTime(h: 09, m: 56)),
                BusScheduleEntry(time: BusScheduleTime(h: 12, m: 05)),
                BusScheduleEntry(time: BusScheduleTime(h: 12, m: 15)),
                BusScheduleEntry(time: BusScheduleTime(h: 12, m: 23)),
                BusScheduleEntry(time: BusScheduleTime(h: 12, m: 26)),
                BusScheduleEntry(time: BusScheduleTime(h: 12, m: 35)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 23)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 26)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 33)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 36)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 45)),
                BusScheduleEntry(time: BusScheduleTime(h: 13, m: 55)),
                BusScheduleEntry(time: BusScheduleTime(h: 15, m: 40)),
                BusScheduleEntry(time: BusScheduleTime(h: 15, m: 53)),
                BusScheduleEntry(time: BusScheduleTime(h: 15, m: 56)),
                BusScheduleEntry(time: BusScheduleTime(h: 16, m: 05)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 23)),
                BusScheduleEntry(time: BusScheduleTime(h: 18, m: 26))
            ]),
    ])



let busRoute4 = BusRoute(
    start: "欣园", end: "科研楼", isPeak: true, schedules: [BusSchedule(
        type: BusScheduleType.WorkingDay, entries: [
            BusScheduleEntry(time: BusScheduleTime(h: 07, m: 35)),
            BusScheduleEntry(time: BusScheduleTime(h: 07, m: 43)),
            BusScheduleEntry(time: BusScheduleTime(h: 07, m: 55)),
            BusScheduleEntry(time: BusScheduleTime(h: 09, m: 53)),
            BusScheduleEntry(time: BusScheduleTime(h: 09, m: 56)),
            BusScheduleEntry(time: BusScheduleTime(h: 10, m: 03)),
            BusScheduleEntry(time: BusScheduleTime(h: 10, m: 06)),
            BusScheduleEntry(time: BusScheduleTime(h: 12, m: 05)),
            BusScheduleEntry(time: BusScheduleTime(h: 12, m: 13)),
            BusScheduleEntry(time: BusScheduleTime(h: 12, m: 16)),
            BusScheduleEntry(time: BusScheduleTime(h: 12, m: 25)),
            BusScheduleEntry(time: BusScheduleTime(h: 12, m: 33)),
            BusScheduleEntry(time: BusScheduleTime(h: 12, m: 36)),
            BusScheduleEntry(time: BusScheduleTime(h: 12, m: 50)),
            BusScheduleEntry(time: BusScheduleTime(h: 13, m: 45)),
            BusScheduleEntry(time: BusScheduleTime(h: 13, m: 53)),
            BusScheduleEntry(time: BusScheduleTime(h: 13, m: 56)),
            BusScheduleEntry(time: BusScheduleTime(h: 14, m: 15)),
            BusScheduleEntry(time: BusScheduleTime(h: 15, m: 50)),
            BusScheduleEntry(time: BusScheduleTime(h: 16, m: 03)),
            BusScheduleEntry(time: BusScheduleTime(h: 16, m: 06)),
            BusScheduleEntry(time: BusScheduleTime(h: 18, m: 05)),
            BusScheduleEntry(time: BusScheduleTime(h: 18, m: 13)),
            BusScheduleEntry(time: BusScheduleTime(h: 18, m: 16)),
            BusScheduleEntry(time: BusScheduleTime(h: 18, m: 26)),
            BusScheduleEntry(time: BusScheduleTime(h: 18, m: 40)),
            BusScheduleEntry(time: BusScheduleTime(h: 20, m: 55)),
            BusScheduleEntry(time: BusScheduleTime(h: 21, m: 03)),
            BusScheduleEntry(time: BusScheduleTime(h: 21, m: 53)),
            BusScheduleEntry(time: BusScheduleTime(h: 21, m: 56)),
            BusScheduleEntry(time: BusScheduleTime(h: 22, m: 10))
        ]
    )])


let busRoute5 = BusRoute(
    start: "智园", end: "荔园", isPeak: false, schedules: [BusSchedule(
        type: BusScheduleType.WorkingDay, entries: [
            BusScheduleEntry(time: BusScheduleTime(h: 11, m: 50)),
            BusScheduleEntry(time: BusScheduleTime(h: 17, m: 45))
        ]
    )])


let allRoutes = [
    busRoute1,
    busRoute2,
    busRoute3,
    busRoute4,
    busRoute5
]
